config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    resources :schedules
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :schedules, dependent: :destroy
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @schedules = @blog.schedules.order(created_at: :desc)
    @schedule = @blog.schedules.build
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_blog, only: [:create, :edit, :update]
  def create
    # Blogをパラメータの値から探し出し,Blogに紐づくcommentsとしてbuildします。
    # @blog = Blog.find(params[:blog_id])
    @schedule = @blog.schedules.build(schedule_params)
    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @schedule.save
        # format.html { redirect_to blog_path(@blog) }
        format.js { render :index }
      else
        format.html { redirect_to blog_path(@blog), notice: '投稿できませんでした...' }
      end
    end
  end

  def edit
    @schedule = @blog.schedules.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    @schedule = @blog.schedules.find(params[:id])
    respond_to do |format|
      if @schedule.update(schedule_params)
        flash.now[:notice] = 'コメントが編集されました'
        format.js { render :index }
      else
        flash.now[:notice] = 'コメントの編集に失敗しました'
        format.js { render :edit_error }
      end
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end

  private
  # ストロングパラメーター
  def schedule_params
    params.require(:schedule).permit(:blog_id, :serial_number, :line_on)
  end

  def set_blog
    @blog = Blog.find(params[:blog_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

  <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
  <%= render partial: 'schedules/form', locals: { schedule: @schedule, blog: @blog } %>

  <div id="schedules_area">
    <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
    <%= render partial: 'schedules/index', locals: { schedules: @schedules, blog: @blog } %>
  </div>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/_edit.html.erb
<%= form_with(model: [blog, schedule]) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :serial_number, id: "schedule_serial_number_#{blog.id}" %>
    <%= form.label :serial_number %>
  </div>
  <div class="field">
    <%= form.date_field :line_on, id: "schedule_line_on_#{blog.id}" %>
    <%= form.label :line_on %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/_form.html.erb
<!-- この記述がblogのshow画面に表示されるコメント入力欄になります -->
<%= form_with(model: [blog, schedule]) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-2">
      <div class="field">
        <%= form.label :serial_number %>
        <%= form.text_field :serial_number %>
      </div>
    </div>
    <div class="col-2">
      <div class="field">
        <%= form.label :line_on %>
        <%= form.date_field :line_on %>
      </div>
    </div>
        <div class="col-2">
      <div class="field">
        <%= form.label :line_on %>
        <%= form.date_field :line_on %>
      </div>
    </div>
        <div class="col-2">
      <div class="field">
        <%= form.label :line_on %>
        <%= form.date_field :line_on %>
      </div>
    </div>
        <div class="col-2">
      <div class="field">
        <%= form.label :line_on %>
        <%= form.date_field :line_on %>
      </div>
    </div>
    <div class="col-2">
      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>

  <ul class="form">
    <li>
      <div class="field">
        <%= form.label :serial_number %><br>
        <%= form.text_field :serial_number %>
      </div>
    </li>
    <li>
      <div class="field">
        <%= form.label :line_on %><br>
        <%= form.date_field :line_on %>
      </div>
    </li>
    <li>
      <div class="field">
        <%= form.label :line_on %><br>
        <%= form.date_field :line_on %>
      </div>
    </li>
    <li>
      <div class="field">
        <%= form.label :line_on %><br>
        <%= form.date_field :line_on %>
      </div>
    </li>
    <li>
      <div class="field">
        <%= form.label :line_on %><br>
        <%= form.date_field :line_on %>
      </div>
    </li>
    <li>
      <div class="actions">
        <%= form.submit %>
      </div>
    </li>
  </ul>
<% end %>

app/views/schedules/_index.html.erb
  <% schedules.each do |schedule| %>
    <% if schedule.id.present? %>
      <div class="row">
        <div class="schedule-content" id ="this_schedule_<%= schedule.id %>"></div>
        <div class="col-2">
          <%= schedule.serial_number %>
        </div>
        <div class="col-2">
          <%= schedule.line_on %>
        </div>
        <div class="col-2">
          <%= schedule.line_on %>
        </div>
        <div class="col-2">
          <%= schedule.line_on %>
        </div>
        <div class="col-2">
          <%= schedule.line_on %>
        </div>
        <div class="col-1">
        <%= link_to "編集", edit_blog_schedule_path(blog, schedule), remote: true %>
        </div>
        <div class="col-1">
        <%= link_to "削除", blog_schedule_path(schedule.blog_id, schedule.id), method: :delete, remote: true,
                              data: { confirm: "本当に削除しますか?"} %>
        </div>
      </div>
    <% end %>
  <% end %>

app/views/schedules/create.html.erb
<h1>Schedules#create</h1>
<p>Find me in app/views/schedules/create.html.erb</p>

app/views/schedules/edit.js.erb
$("#this_schedule_<%= @schedule.id %>").replaceWith("<%= j render 'schedules/edit', blog: @blog, schedule: @schedule %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/schedules/index.js.erb
$("#schedules_area").html("<%= j(render 'schedules/index', { schedules: @schedule.blog.schedules.order(created_at: :desc), blog: @schedule.blog }) %>");
$("textfield").val('');
$("datetimefield").val('');
$("#notice").html("<%= j flash[:notice] %>");